### PR TITLE
Update PyO3 0.20 -> 0.22 & Python 3.13

### LINKED ISSUE #165: Please consider porting to the latest PyO3
Please consider porting to the latest PyO3, currently 0.22, which has full support for Python 3.13.

https://pyo3.rs/v0.22.0/migration#from-020-to-021
https://pyo3.rs/v0.22.0/migration#from-021-to-022

### PR DESCRIPTION
**Pull request by milesgranger**
Will close #165 
and followup to #167

### CODE REVIEW

**Comment by martindurant** [comment]
This is one impressive PR!

**Comment by lgray** [comment]
Whoa! Thanks!

**Comment by lgray** [comment]
@milesgranger I couldn't really divine the situation from the internet so I'm asking you, but what are the steps towards 3.13 
freethreaded support after this?

**Comment by milesgranger** [comment]
Good question. :) I suppose it's mostly conforming to any API changes PyO3 implements. ie https://github.com/PyO3/pyo3/issues/4265; then anywhere we're doing unsavory GIL stuff outside of PyO3 which at first glance is _maybe_ some stuff in the `PythonBuffer`, but nothing atrocious.

**Pull request merged**
